from func.lang.c import run_c
from func.lang.cpp import run_cpp
from func.lang.bash import run_bash
from func.lang.node import run_node
from func.lang.perl import run_perl
from func.lang.ruby import run_ruby
from func.lang.build import run_build
from func.lang.python import run_python
from func.lang.busybox import run_busybox
